logger:
  level: "info"

server:
  host: "0.0.0.0"
  port: "8080"

db:
  user: "postgres"
  password: "postgres"
  name: "marketplace_auth"
  host: "db"
  port: "5432"
  sslmode: "disable"

jwt:
  secret_key: "your-super-secret-jwt-key-here"
  expires_in: 24
