version: '3.9'

services:
  db:
    image: postgres:16-alpine
    env_file: .env  # Explicit load
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-marketplace_auth}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}", "-d", "${POSTGRES_DB:-marketplace_auth}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - backend

  migrator:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}
    command: >
      sh -c './migrate -path /migrations -database "$POSTGRES_DSN" -verbose up'


    volumes:
      - ./migrations:/migrations
    restart: no
    networks:
      - backend

  app:
    build: .
    depends_on:
      migrator:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend: {}

volumes:
  pgdata: {}